define(
   ({
    id: 'ID',
    state: "Koordinātas pēc noklusējuma tiks rādītas pašreizējās kartes koordinātu sistēmā. Lai koordinātes iegūtu citās koordinātu sistēmās, tās ir jāpievieno un jānorāda attiecīgās transformācijas.",
    outputUnit: "Izvades vienība",
    wkid: "Izvades WKID",
    label: "Izvades koordinātu sistēmas nosaukums",
    transformationWkid: "Transformācijas WKID",
    transformationLabel: "Transformācijas kartes teksts",
    transformForward: "Transformēt uz priekšu",
    actions: "Darbības",
    warning: "Ievadiet derīgu telpiskās atskaites WKID!",
    tfWarning: "Ievadiet derīgu dotā lieluma transformācijas WKID!",
    spinnerLabel: "Noapaļot koordinātas līdz: ",
    eyeDecimalLabel: "Noapaļot acu augstumu līdz: ",
    decimalPlace: "decimālvietas",
    separator: "Rādīt tūkstošdaļu atdalītājus",
    getVersionError: "Nevar iegūt ģeometrijas pakalpojuma versiju",

    add: "Pievienot izvades koordinātu sistēmu",
    edit: "Rediģēt koordinātu sistēmu",
    output: "Izvades koordinātu sistēma",
    cName: "Koordinātu sistēmas nosaukums",
    units: "Rādāmās vienības: ",
    datum: "Dotā lieluma transformācija",
    tName: "Transformācijas nosaukums",
    tWKIDPlaceHolder: "Transformācijas WKID",
    forward: "Izmantot transformāciju uz priekšu",
    ok: "Labi",
    cancel: 'Atcelt',
    olderVersion: "Ģeometrijas pakalpojums neatbalsta transformācijas darbību",
    REPEATING_ERROR: " Koordinātu sistēma pastāv izvades sarakstā.",

    Default: "Noklusējums",
    Inches: "Collas",
    Foot: "Pēdas",
    Yards: "Jardi",
    Miles: "Jūdzes",
    Nautical_Miles: "Jūras jūdzes",
    Millimeters: "Milimetri",
    Centimeters: "Centimetri",
    Meter: "Metri",
    Kilometers: "Kilometri",
    Decimeters: "Decimetri",
    Decimal_Degrees: "Decimālgrādi",
    Degree_Minutes_Seconds: "Grādi minūtes sekundes",
    MGRS: "MGRS",
    USNG: "USNG"
  })
);